# Generated by Django 4.0 on 2023-09-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    """Implemenation of Migration for uploading image"""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='decoding')),
            ],
        ),
    ]
